openapi: 3.0.0
info:
  title: Courier Management API
  version: 1.0.0
  description: CRUD for couriers with filters, pagination and relation to users.
servers:
  - url: /api
    description: Base API path
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserShort:
      type: object
      properties:
        _id:
          type: string
          example: "665fd9b2a1b2c3d4e5f60789"
        fullName:
          type: string
          example: "John Doe"
        phone:
          type: string
          example: "+1234567890"
        role:
          type: string
          enum: [admin, dispatcher, courier, customer]
          example: courier
        isActive:
          type: boolean
          example: true
    Courier:
      type: object
      properties:
        _id:
          type: string
        user:
          $ref: '#/components/schemas/UserShort'
        city:
          type: string
          example: "New York"
        isAvailable:
          type: boolean
          example: true
        rating:
          type: number
          format: float
          minimum: 0
          maximum: 5
          example: 4.7
        vehicleType:
          type: string
          enum: [car, bike, foot, scooter, other]
          example: bike
        notes:
          type: string
          example: "Can deliver fragile items"
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CourierListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Courier'
        total:
          type: integer
          example: 42
        page:
          type: integer
          example: 1
        limit:
          type: integer
          example: 20
    Error:
      type: object
      properties:
        error:
          type: string
        details:
          type: string
paths:
  /couriers:
    get:
      summary: List couriers with filters and pagination
      description: Returns a paginated list of couriers with optional filters and sorting.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Search by user fullName or phone (case-insensitive).
        - in: query
          name: city
          schema:
            type: string
          description: Filter by courier city (exact match).
        - in: query
          name: isAvailable
          schema:
            type: boolean
          description: Filter by availability.
        - in: query
          name: ratingFrom
          schema:
            type: number
          description: Minimal rating (inclusive).
        - in: query
          name: ratingTo
          schema:
            type: number
          description: Maximal rating (inclusive).
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number (1-based).
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
          description: Page size (1..100).
        - in: query
          name: sortBy
          schema:
            type: string
            enum: [createdAt, rating, fullName, city, isAvailable]
            default: createdAt
          description: Sort field.
        - in: query
          name: sortDir
          schema:
            type: string
            enum: [asc, desc]
            default: desc
          description: Sort direction.
      responses:
        '200':
          description: List of couriers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourierListResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new courier
      description: Create a courier profile. If userId is not provided, a new user with role=courier will be created. Requires roles admin|dispatcher.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: Existing user id to attach as courier.
                fullName:
                  type: string
                  description: Required if userId not provided.
                phone:
                  type: string
                  description: Required if userId not provided; must be unique across users.
                email:
                  type: string
                city:
                  type: string
                isAvailable:
                  type: boolean
                rating:
                  type: number
                vehicleType:
                  type: string
                  enum: [car, bike, foot, scooter, other]
                notes:
                  type: string
      responses:
        '201':
          description: Created courier
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courier'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict (duplicate phone or courier exists)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /couriers/{id}:
    get:
      summary: Get courier by id
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Courier details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courier'
        '400':
          description: Invalid id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update courier
      description: Update courier profile and (optionally) related user fields (fullName, phone, email). Requires roles admin|dispatcher.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                city:
                  type: string
                isAvailable:
                  type: boolean
                rating:
                  type: number
                vehicleType:
                  type: string
                  enum: [car, bike, foot, scooter, other]
                notes:
                  type: string
                user:
                  type: object
                  properties:
                    fullName:
                      type: string
                    phone:
                      type: string
                    email:
                      type: string
      responses:
        '200':
          description: Updated courier
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courier'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict (e.g., phone already used)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Remove courier
      description: Soft delete by default (sets user.isActive=false and courier.isAvailable=false). If query hard=true, hard deletes courier document and deactivates user.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: hard
          required: false
          schema:
            type: boolean
          description: If true, performs a hard delete of the courier document.
      responses:
        '200':
          description: Delete result
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  deleted:
                    type: boolean
                  mode:
                    type: string
                    enum: [soft, hard]
                  userDeactivated:
                    type: boolean
        '400':
          description: Invalid id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
security:
  - bearerAuth: []
